tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"
brew "aria2"
brew "autoconf"
brew "automake"
brew "bash"
brew "bash-completion"
brew "fish"
brew "gettext", link: true
brew "gnupg"
brew "htop"
brew "httpd"
brew "libtool"
brew "mas"
brew "mosh"
brew "mysql"
brew "nginx"
brew "nmap"
brew "node"
brew "pandoc"
brew "pinentry-mac"
brew "python"
brew "speedtest-cli"
brew "ssh-copy-id"
brew "stow"
brew "syncthing", restart_service: true
brew "tldr"
brew "wget"
brew "yubico-piv-tool"
brew "homebrew/php/phpmyadmin"
cask "appcleaner"
cask "arq"
cask "astro"
cask "bartender"
cask "brackets"
cask "caffeine"
cask "delibar"
cask "etcher"
cask "firefox"
cask "fluid"
cask "ghost"
cask "github"
cask "google-chrome"
cask "grammarly"
cask "hyper"
cask "iterm2"
cask "keybase"
cask "little-snitch"
cask "mailmate"
cask "mojibar"
cask "notion"
cask "plexamp"
cask "signal"
cask "skype"
cask "slack"
cask "spectacle"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "swinsian"
cask "telegram-desktop"
cask "the-unarchiver"
cask "transmit"
cask "vidyo"
cask "viscosity"
cask "vlc"
cask "xld"
cask "caskroom/fonts/font-clear-sans"
cask "caskroom/fonts/font-firacode-nerd-font"
cask "caskroom/fonts/font-hack"
cask "caskroom/fonts/font-inconsolata"
cask "caskroom/fonts/font-m-plus"
cask "caskroom/fonts/font-open-sans"
cask "caskroom/fonts/font-roboto"
mas "1Password", id: 443987910
mas "Annotate", id: 918207447
mas "Bear", id: 1091189122
mas "Better", id: 1121192229
mas "Fantastical 2", id: 975937182
mas "iA Writer", id: 775737590
mas "Keynote", id: 409183694
mas "MarsEdit", id: 1198319098
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Reeder", id: 880001334
mas "Tweetbot", id: 557168941
mas "Twitter", id: 409789998
mas "WhatsApp", id: 1147396723
