tap "caskroom/cask"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "colindean/fonts-nonfree"
tap "homebrew/bundle"
tap "homebrew/completions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "kalikaneko/bitmask"
tap "kevwil/patches"
tap "neomutt/neomutt"
tap "sgeb/mutt"
brew "sqlite"
brew "aircrack-ng"
brew "antigen"
brew "apm-bash-completion"
brew "aria2"
brew "autoconf"
brew "automake"
brew "caddy"
brew "freetype"
brew "fontconfig"
brew "glib"
brew "pixman"
brew "cairo"
brew "curl"
brew "doxygen"
brew "exa"
brew "lame"
brew "perl"
brew "git"
brew "ffmpeg"
brew "pcre2"
brew "fish"
brew "gdbm"
brew "gifsicle"
brew "pkg-config"
brew "gmime"
brew "gnupg"
brew "pth"
brew "gpg-agent"
brew "htop"
brew "hugo"
brew "id3ed"
brew "id3lib"
brew "xz"
brew "lftp"
brew "libevent"
brew "libusb-compat"
brew "libyaml"
brew "mas"
brew "mobile-shell"
brew "msmtp"
brew "mtr"
brew "neofetch"
brew "nmap"
brew "node"
brew "ruby"
brew "talloc"
brew "notmuch"
brew "offlineimap", restart_service: true
brew "pandoc"
brew "pinentry-mac"
brew "speedtest-cli"
brew "stow"
brew "syncthing", restart_service: true
brew "terminal-notifier"
brew "tldr"
brew "tmux"
brew "tokyo-cabinet"
brew "tor"
brew "torsocks"
brew "tree"
brew "utf8proc"
brew "vim"
brew "wget"
brew "youtube-dl"
brew "z"
brew "kalikaneko/bitmask/bitmask"
brew "neomutt/neomutt/neomutt", args: ["with-notmuch-patch"]
cask "appcleaner"
cask "atext"
cask "atom"
cask "bartender"
cask "brackets"
cask "caffeine"
cask "cloak"
cask "firefox"
cask "flux"
cask "font-clear-sans"
cask "font-firacode-nerd-font"
cask "font-hack"
cask "font-inconsolata"
cask "font-m-plus"
cask "font-microsoft-office"
cask "font-open-sans"
cask "font-roboto"
cask "ghost"
cask "google-chrome"
cask "handbrake"
cask "hazel"
cask "iterm2"
cask "mailmate"
cask "marsedit"
cask "micro-snitch"
cask "mojibar"
cask "notational-velocity"
cask "nvalt"
cask "papers"
cask "plex-media-server"
cask "private-internet-access"
cask "qsyncthingtray"
cask "simplenote"
cask "skype"
cask "slack-beta"
cask "spectacle"
cask "spotify"
cask "standard-notes"
cask "steam"
cask "sublime-text"
cask "swinsian"
cask "telegram-desktop"
cask "the-unarchiver"
cask "tomahawk"
cask "torbrowser"
cask "transmission"
cask "transmit"
cask "tunnelbear"
cask "tunnelblick"
cask "viscosity"
cask "vlc"
cask "xld"
mas "1Password", id: 443987910
mas "Annotate", id: 918207447
mas "Bear", id: 1091189122
mas "Better", id: 1121192229
mas "Deckset", id: 847496013
mas "Fantastical 2", id: 975937182
mas "GIF Brewery 3", id: 1081413713
mas "GIPHY CAPTURE", id: 668208984
mas "iA Writer", id: 775737590
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Reeder", id: 880001334
mas "Spillo", id: 873245660
mas "Tag Editor Free", id: 984278082
mas "Todoist", id: 585829637
mas "Tweetbot", id: 557168941
mas "WhatsApp", id: 1147396723
